version: "3"
services:
  # db:
  #   image: "postgres:11.2"
  #   environment:
  #     - POSTGRES_USER=db_user
  #     - POSTGRES_PASSWORD=db_password
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/nginx/certs

  backend:
    restart: always
    container_name: backend
    build: ./backend
    expose:
      - 5000
    volumes:
      - ./backend:/usr/src/app
    environment:
      - APP_ENV=${APP_ENV}
    # depends_on:
    #   - db