version: "3"
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=skeduler_db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    ports:
      - 5432:5432

  backend:
    restart: always
    container_name: backend
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    build: ./backend
    expose:
      - 5000
    # ports:
    #   - 5000:5000
    # volumes:
    #   - ./backend:/usr/src/app
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/nginx/certs
    depends_on:
      - backend
volumes:
  postgres_data: