version: "3"
services:
  postgres_db:
    container_name: postgres_db
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=skeduler_db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    ports:
      - 5433:5432

  backend:
    restart: always
    container_name: backend
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    build: ./backend
    expose:
      - 5000
    environment:
      - APP_ENV=Production
    depends_on:
      - postgres_db

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/nginx/certs
    depends_on:
      - backend
volumes:
  postgres_data: