version: "3"
services:
  postgres_db:
    container_name: postgres_db
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=skeduler_db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    ports:
      - 5433:5432

volumes:
  postgres_data: