version: "3"
services:
  db:
    image: "postgres:11.2"
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/ssl:/etc/nginx/certs

  server:
    restart: always
    container_name: server
    build: ./server
    expose:
      - 5000
    volumes:
      - ./server:/usr/src/app
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - db