"""empty message

Revision ID: 03364f8a0026
Revises: f952df987ad0
Create Date: 2021-02-04 07:45:54.439152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "03364f8a0026"
down_revision = "f952df987ad0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_leave",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("employee_id", sa.String(length=36), nullable=False),
        sa.Column("start_day", sa.Date(), nullable=False),
        sa.Column("end_day", sa.Date(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum("PAID_LEAVE", "UNPAID_LEAVE", name="leavereason"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING_APPROVAL", "CONFIRMED", "DECLINED", name="leavestatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["employee_id"], ["employee.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("employee_leave")
    # ### end Alembic commands ###
