"""empty message

Revision ID: 0746a5e32c6d
Revises: 8f2d96f8781e
Create Date: 2021-02-26 09:35:02.933019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0746a5e32c6d"
down_revision = "8f2d96f8781e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule", sa.Column("infeasible_cts", sa.String(length=256), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule", "infeasible_cts")
    # ### end Alembic commands ###
