"""empty message

Revision ID: 0fc69ab847af
Revises: f2ce5acff29f
Create Date: 2021-03-05 14:24:20.499012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0fc69ab847af"
down_revision = "f2ce5acff29f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_penalty",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("schedule_id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.String(length=128), nullable=False),
        sa.Column("penalty", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["schedule_id"], ["schedule.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schedule_penalty")
    # ### end Alembic commands ###
