"""empty message

Revision ID: 251a07656dbb
Revises: b3cc156ff4bd
Create Date: 2021-02-04 18:10:29.604314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "251a07656dbb"
down_revision = "b3cc156ff4bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_event",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("employee_id", sa.String(length=36), nullable=False),
        sa.Column("shift_id", sa.String(length=36), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "PAID_LEAVE", "UNPAID_LEAVE", "HOLIDAY", "ILLNESS", name="eventtype"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CONFIRMED", "DECLINED", name="eventstatus"),
            nullable=False,
        ),
        sa.Column(
            "nature",
            sa.Enum("MANDATORY", "IMPORTANT", "WANTED", "PREFERED", name="eventnature"),
            nullable=False,
        ),
        sa.Column("is_desired", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employee.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shift_id"], ["shift.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("employee_leave")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_leave",
        sa.Column("id", mysql.VARCHAR(length=36), nullable=False),
        sa.Column("employee_id", mysql.VARCHAR(length=36), nullable=False),
        sa.Column("reason", mysql.ENUM("PAID_LEAVE", "UNPAID_LEAVE"), nullable=False),
        sa.Column(
            "status",
            mysql.ENUM("PENDING_APPROVAL", "CONFIRMED", "DECLINED"),
            nullable=False,
        ),
        sa.Column("duration", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("start_date", sa.DATE(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.id"],
            name="employee_leave_ibfk_1",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("employee_event")
    # ### end Alembic commands ###
