"""empty message

Revision ID: 44cb09aa144a
Revises: 4944f50941e7
Create Date: 2021-03-09 17:02:52.008830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "44cb09aa144a"
down_revision = "4944f50941e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule", "status")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule",
        sa.Column(
            "status",
            postgresql.ENUM(
                "UNKNOWN",
                "MODEL_INVALID",
                "FEASIBLE",
                "INFEASIBLE",
                "OPTIMAL",
                name="solverstatus",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
