"""empty message

Revision ID: 4944f50941e7
Revises: 0fc69ab847af
Create Date: 2021-03-09 16:01:37.083763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4944f50941e7"
down_revision = "0fc69ab847af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule", "infeasible_cts")
    op.add_column("schedule_penalty", sa.Column("excess", sa.Integer(), nullable=True))
    op.add_column(
        "schedule_penalty", sa.Column("is_linear", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE schedule_penalty SET is_linear = false")
    op.alter_column("schedule_penalty", "is_linear", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule_penalty", "is_linear")
    op.drop_column("schedule_penalty", "excess")
    op.add_column(
        "schedule",
        sa.Column(
            "infeasible_cts", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
