"""empty message

Revision ID: 8f2d96f8781e
Revises: d4459eef50cb
Create Date: 2021-02-18 19:04:21.155975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8f2d96f8781e"
down_revision = "d4459eef50cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "employee_skill_shift_id_fkey", "employee_skill", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "employee_skill", "shift", ["shift_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "employee_skill", type_="foreignkey")
    op.create_foreign_key(
        "employee_skill_shift_id_fkey", "employee_skill", "shift", ["shift_id"], ["id"]
    )
    # ### end Alembic commands ###
