"""empty message

Revision ID: a5877b49b0ee
Revises: 678149ac23cf
Create Date: 2021-02-17 19:53:42.039184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a5877b49b0ee"
down_revision = "678149ac23cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "company_sequence_rule_company_id_fkey",
        "company_sequence_rule",
        type_="foreignkey",
    )
    op.create_foreign_key(None, "company_sequence_rule", "shift", ["shift_id"], ["id"])
    op.create_foreign_key(
        None, "company_sequence_rule", "company", ["company_id"], ["id"]
    )
    op.drop_constraint(
        "company_transition_rule_from_shift_id_fkey",
        "company_transition_rule",
        type_="foreignkey",
    )
    op.drop_constraint(
        "company_transition_rule_company_id_fkey",
        "company_transition_rule",
        type_="foreignkey",
    )
    op.drop_constraint(
        "company_transition_rule_to_shift_id_fkey",
        "company_transition_rule",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "company_transition_rule", "shift", ["from_shift_id"], ["id"]
    )
    op.create_foreign_key(
        None, "company_transition_rule", "shift", ["to_shift_id"], ["id"]
    )
    op.create_foreign_key(
        None, "company_transition_rule", "company", ["company_id"], ["id"]
    )
    op.drop_constraint("day_company_id_fkey", "day", type_="foreignkey")
    op.create_foreign_key(None, "day", "company", ["company_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "day", type_="foreignkey")
    op.create_foreign_key(
        "day_company_id_fkey",
        "day",
        "company",
        ["company_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "company_transition_rule", type_="foreignkey")
    op.drop_constraint(None, "company_transition_rule", type_="foreignkey")
    op.drop_constraint(None, "company_transition_rule", type_="foreignkey")
    op.create_foreign_key(
        "company_transition_rule_to_shift_id_fkey",
        "company_transition_rule",
        "shift",
        ["to_shift_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "company_transition_rule_company_id_fkey",
        "company_transition_rule",
        "company",
        ["company_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "company_transition_rule_from_shift_id_fkey",
        "company_transition_rule",
        "shift",
        ["from_shift_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "company_sequence_rule", type_="foreignkey")
    op.drop_constraint(None, "company_sequence_rule", type_="foreignkey")
    op.create_foreign_key(
        "company_sequence_rule_company_id_fkey",
        "company_sequence_rule",
        "company",
        ["company_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
