"""empty message

Revision ID: b3cc156ff4bd
Revises: 71707b02e676
Create Date: 2021-02-04 13:55:27.327548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b3cc156ff4bd"
down_revision = "71707b02e676"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employee_leave", sa.Column("start_date", sa.Date(), nullable=False))
    op.drop_column("employee_leave", "start_day")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employee_leave", sa.Column("start_day", sa.DATE(), nullable=False))
    op.drop_column("employee_leave", "start_date")
    # ### end Alembic commands ###
