"""empty message

Revision ID: b89a8843058d
Revises: a5877b49b0ee
Create Date: 2021-02-17 20:34:45.553600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b89a8843058d"
down_revision = "a5877b49b0ee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "company_sequence_rule_company_id_fkey",
        "company_sequence_rule",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "company_sequence_rule",
        "company",
        ["company_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "company_transition_rule_company_id_fkey",
        "company_transition_rule",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "company_transition_rule",
        "company",
        ["company_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("day_company_id_fkey", "day", type_="foreignkey")
    op.create_foreign_key(
        None, "day", "company", ["company_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "employee", sa.Column("company_id", sa.String(length=36), nullable=False)
    )
    op.create_foreign_key(
        None, "employee", "company", ["company_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "employee_event_shift_id_fkey", "employee_event", type_="foreignkey"
    )
    op.drop_constraint(
        "employee_event_employee_id_fkey", "employee_event", type_="foreignkey"
    )
    op.create_foreign_key(None, "employee_event", "shift", ["shift_id"], ["id"])
    op.create_foreign_key(None, "employee_event", "employee", ["employee_id"], ["id"])
    op.drop_constraint(
        "employee_skill_shift_id_fkey", "employee_skill", type_="foreignkey"
    )
    op.drop_constraint(
        "employee_skill_employee_id_fkey", "employee_skill", type_="foreignkey"
    )
    op.create_foreign_key(None, "employee_skill", "shift", ["shift_id"], ["id"])
    op.create_foreign_key(None, "employee_skill", "employee", ["employee_id"], ["id"])
    op.add_column(
        "shift", sa.Column("company_id", sa.String(length=36), nullable=False)
    )
    op.create_foreign_key(
        None, "shift", "company", ["company_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "shift", type_="foreignkey")
    op.drop_column("shift", "company_id")
    op.drop_constraint(None, "employee_skill", type_="foreignkey")
    op.drop_constraint(None, "employee_skill", type_="foreignkey")
    op.create_foreign_key(
        "employee_skill_employee_id_fkey",
        "employee_skill",
        "employee",
        ["employee_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "employee_skill_shift_id_fkey",
        "employee_skill",
        "shift",
        ["shift_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "employee_event", type_="foreignkey")
    op.drop_constraint(None, "employee_event", type_="foreignkey")
    op.create_foreign_key(
        "employee_event_employee_id_fkey",
        "employee_event",
        "employee",
        ["employee_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "employee_event_shift_id_fkey",
        "employee_event",
        "shift",
        ["shift_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "employee", type_="foreignkey")
    op.drop_column("employee", "company_id")
    op.drop_constraint(None, "day", type_="foreignkey")
    op.create_foreign_key(
        "day_company_id_fkey", "day", "company", ["company_id"], ["id"]
    )
    op.drop_constraint(None, "company_transition_rule", type_="foreignkey")
    op.create_foreign_key(
        "company_transition_rule_company_id_fkey",
        "company_transition_rule",
        "company",
        ["company_id"],
        ["id"],
    )
    op.drop_constraint(None, "company_sequence_rule", type_="foreignkey")
    op.create_foreign_key(
        "company_sequence_rule_company_id_fkey",
        "company_sequence_rule",
        "company",
        ["company_id"],
        ["id"],
    )
    # ### end Alembic commands ###
