"""empty message

Revision ID: c0e852063259
Revises: 0746a5e32c6d
Create Date: 2021-02-26 18:23:45.916865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c0e852063259"
down_revision = "0746a5e32c6d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("schedule", sa.Column("objective", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule", "objective")
    # ### end Alembic commands ###
