"""empty message

Revision ID: c3ace819c611
Revises: b89a8843058d
Create Date: 2021-02-18 14:55:02.228250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3ace819c611"
down_revision = "b89a8843058d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule", sa.Column("company_id", sa.String(length=36), nullable=False)
    )
    op.create_foreign_key(
        None, "schedule", "company", ["company_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "schedule", type_="foreignkey")
    op.drop_column("schedule", "company_id")
    # ### end Alembic commands ###
