"""empty message

Revision ID: ca683a041c2d
Revises: c3ace819c611
Create Date: 2021-02-18 17:16:09.146174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ca683a041c2d"
down_revision = "c3ace819c611"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shift", sa.Column("cover_wednesday", sa.Integer(), nullable=True))
    op.drop_column("shift", "cover_wednesay")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shift",
        sa.Column("cover_wednesay", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("shift", "cover_wednesday")
    # ### end Alembic commands ###
