"""empty message

Revision ID: d4459eef50cb
Revises: ca683a041c2d
Create Date: 2021-02-18 19:02:42.442795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d4459eef50cb"
down_revision = "ca683a041c2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "employee_skill_employee_id_fkey", "employee_skill", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "employee_skill", "employee", ["employee_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "employee_skill", type_="foreignkey")
    op.create_foreign_key(
        "employee_skill_employee_id_fkey",
        "employee_skill",
        "employee",
        ["employee_id"],
        ["id"],
    )
    # ### end Alembic commands ###
