"""empty message

Revision ID: da6eb06df282
Revises: c0e852063259
Create Date: 2021-02-27 16:13:47.830251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = "da6eb06df282"
down_revision = "c0e852063259"
branch_labels = None
depends_on = None


def upgrade():
    employeeavailability = ENUM(
        "WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"
    )
    employeeavailability.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee",
        sa.Column(
            "availability_friday",
            sa.Enum("WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"),
            default="NOT_WORKING",
        ),
    )
    op.add_column(
        "employee",
        sa.Column(
            "availability_monday",
            sa.Enum("WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"),
            default="NOT_WORKING",
        ),
    )
    op.add_column(
        "employee",
        sa.Column(
            "availability_saturday",
            sa.Enum("WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"),
            default="NOT_WORKING",
        ),
    )
    op.add_column(
        "employee",
        sa.Column(
            "availability_sunday",
            sa.Enum("WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"),
            default="NOT_WORKING",
        ),
    )
    op.add_column(
        "employee",
        sa.Column(
            "availability_thursday",
            sa.Enum("WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"),
            default="NOT_WORKING",
        ),
    )
    op.add_column(
        "employee",
        sa.Column(
            "availability_tuesday",
            sa.Enum("WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"),
            default="NOT_WORKING",
        ),
    )
    op.add_column(
        "employee",
        sa.Column(
            "availability_wednesday",
            sa.Enum("WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"),
            default="NOT_WORKING",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employee", "availability_wednesday")
    op.drop_column("employee", "availability_tuesday")
    op.drop_column("employee", "availability_thursday")
    op.drop_column("employee", "availability_sunday")
    op.drop_column("employee", "availability_saturday")
    op.drop_column("employee", "availability_monday")
    op.drop_column("employee", "availability_friday")
    employeeavailability = ENUM(
        "WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"
    )
    employeeavailability.drop(op.get_bind())
    # ### end Alembic commands ###
