"""empty message

Revision ID: f2ce5acff29f
Revises: da6eb06df282
Create Date: 2021-02-27 18:20:57.842720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f2ce5acff29f"
down_revision = "da6eb06df282"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee",
        sa.Column(
            "availability_friday",
            sa.Enum("WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"),
            nullable=True,
        ),
    )
    op.add_column(
        "employee",
        sa.Column(
            "availability_monday",
            sa.Enum("WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"),
            nullable=True,
        ),
    )
    op.add_column(
        "employee",
        sa.Column(
            "availability_saturday",
            sa.Enum("WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"),
            nullable=True,
        ),
    )
    op.add_column(
        "employee",
        sa.Column(
            "availability_sunday",
            sa.Enum("WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"),
            nullable=True,
        ),
    )
    op.add_column(
        "employee",
        sa.Column(
            "availability_thursday",
            sa.Enum("WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"),
            nullable=True,
        ),
    )
    op.add_column(
        "employee",
        sa.Column(
            "availability_tuesday",
            sa.Enum("WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"),
            nullable=True,
        ),
    )
    op.add_column(
        "employee",
        sa.Column(
            "availability_wednesday",
            sa.Enum("WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"),
            nullable=True,
        ),
    )
    op.drop_column("employee", "available_saturday")
    op.drop_column("employee", "available_sunday")
    op.drop_column("employee", "available_tuesday")
    op.drop_column("employee", "available_friday")
    op.drop_column("employee", "available_thursday")
    op.drop_column("employee", "available_wednesday")
    op.drop_column("employee", "available_monday")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee",
        sa.Column(
            "available_monday",
            postgresql.ENUM(
                "WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "employee",
        sa.Column(
            "available_wednesday",
            postgresql.ENUM(
                "WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "employee",
        sa.Column(
            "available_thursday",
            postgresql.ENUM(
                "WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "employee",
        sa.Column(
            "available_friday",
            postgresql.ENUM(
                "WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "employee",
        sa.Column(
            "available_tuesday",
            postgresql.ENUM(
                "WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "employee",
        sa.Column(
            "available_sunday",
            postgresql.ENUM(
                "WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "employee",
        sa.Column(
            "available_saturday",
            postgresql.ENUM(
                "WORKING", "AVAILABLE", "NOT_WORKING", name="employeeavailability"
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("employee", "availability_wednesday")
    op.drop_column("employee", "availability_tuesday")
    op.drop_column("employee", "availability_thursday")
    op.drop_column("employee", "availability_sunday")
    op.drop_column("employee", "availability_saturday")
    op.drop_column("employee", "availability_monday")
    op.drop_column("employee", "availability_friday")
    # ### end Alembic commands ###
