"""empty message

Revision ID: f952df987ad0
Revises: 29985b41f1be
Create Date: 2021-01-23 16:22:18.130747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f952df987ad0"
down_revision = "29985b41f1be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("schedule", sa.Column("created_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule", "created_at")
    # ### end Alembic commands ###
