"""empty message

Revision ID: 96364376e34f
Revises: d7387d2d3a88
Create Date: 2021-02-04 09:33:05.021226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "96364376e34f"
down_revision = "d7387d2d3a88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "day",
        "name",
        existing_type=mysql.VARCHAR(length=16),
        type_=sa.Enum(
            "MONDAY",
            "TUESDAY",
            "WEDNESDAY",
            "THURSDAY",
            "FRIDAY",
            "SATURDAY",
            "SUNDAY",
            name="day",
        ),
        existing_nullable=True,
    )
    op.drop_index("order", table_name="day")
    op.drop_column("day", "order")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "day",
        sa.Column(
            "order",
            mysql.ENUM(
                "MONDAY",
                "TUESDAY",
                "WEDNESDAY",
                "THURSDAY",
                "FRIDAY",
                "SATURDAY",
                "SUNDAY",
            ),
            nullable=True,
        ),
    )
    op.create_index("order", "day", ["order"], unique=True)
    op.alter_column(
        "day",
        "name",
        existing_type=sa.Enum(
            "MONDAY",
            "TUESDAY",
            "WEDNESDAY",
            "THURSDAY",
            "FRIDAY",
            "SATURDAY",
            "SUNDAY",
            name="day",
        ),
        type_=mysql.VARCHAR(length=16),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
