"""empty message

Revision ID: d7387d2d3a88
Revises: 03364f8a0026
Create Date: 2021-02-04 09:31:48.974266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "d7387d2d3a88"
down_revision = "03364f8a0026"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "day",
        "order",
        existing_type=mysql.INTEGER(),
        type_=sa.Enum(
            "MONDAY",
            "TUESDAY",
            "WEDNESDAY",
            "THURSDAY",
            "FRIDAY",
            "SATURDAY",
            "SUNDAY",
            name="day",
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "day",
        "order",
        existing_type=sa.Enum(
            "MONDAY",
            "TUESDAY",
            "WEDNESDAY",
            "THURSDAY",
            "FRIDAY",
            "SATURDAY",
            "SUNDAY",
            name="day",
        ),
        type_=mysql.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
