"""empty message

Revision ID: dee00e6460d8
Revises: 251a07656dbb
Create Date: 2021-02-05 12:12:50.113352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dee00e6460d8"
down_revision = "251a07656dbb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shift", sa.Column("cover_friday", sa.Integer(), nullable=True))
    op.add_column("shift", sa.Column("cover_monday", sa.Integer(), nullable=True))
    op.add_column("shift", sa.Column("cover_saturday", sa.Integer(), nullable=True))
    op.add_column("shift", sa.Column("cover_sunday", sa.Integer(), nullable=True))
    op.add_column("shift", sa.Column("cover_thursday", sa.Integer(), nullable=True))
    op.add_column("shift", sa.Column("cover_tuesday", sa.Integer(), nullable=True))
    op.add_column("shift", sa.Column("cover_wednesay", sa.Integer(), nullable=True))
    op.add_column(
        "shift",
        sa.Column(
            "shift_importance",
            sa.Enum("MAJOR", "AVERAGE", "MINOR", name="shiftimportance"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shift", "shift_importance")
    op.drop_column("shift", "cover_wednesay")
    op.drop_column("shift", "cover_tuesday")
    op.drop_column("shift", "cover_thursday")
    op.drop_column("shift", "cover_sunday")
    op.drop_column("shift", "cover_saturday")
    op.drop_column("shift", "cover_monday")
    op.drop_column("shift", "cover_friday")
    # ### end Alembic commands ###
